// ─────────────────────────────────────────────────────────────────────────────
// data.js  –  Static reference data: Bible books and translations
// ─────────────────────────────────────────────────────────────────────────────

const BIBLE_BOOKS = [
  // ── Old Testament ──────────────────────────────────────────────────────────
  { name: 'Genesis',          abbr: 'Gen',   testament: 'OT', maxChapters: 50  },
  { name: 'Exodus',           abbr: 'Exod',  testament: 'OT', maxChapters: 40  },
  { name: 'Leviticus',        abbr: 'Lev',   testament: 'OT', maxChapters: 27  },
  { name: 'Numbers',          abbr: 'Num',   testament: 'OT', maxChapters: 36  },
  { name: 'Deuteronomy',      abbr: 'Deut',  testament: 'OT', maxChapters: 34  },
  { name: 'Joshua',           abbr: 'Josh',  testament: 'OT', maxChapters: 24  },
  { name: 'Judges',           abbr: 'Judg',  testament: 'OT', maxChapters: 21  },
  { name: 'Ruth',             abbr: 'Ruth',  testament: 'OT', maxChapters: 4   },
  { name: '1 Samuel',         abbr: '1 Sam', testament: 'OT', maxChapters: 31  },
  { name: '2 Samuel',         abbr: '2 Sam', testament: 'OT', maxChapters: 24  },
  { name: '1 Kings',          abbr: '1 Kgs', testament: 'OT', maxChapters: 22  },
  { name: '2 Kings',          abbr: '2 Kgs', testament: 'OT', maxChapters: 25  },
  { name: '1 Chronicles',     abbr: '1 Chr', testament: 'OT', maxChapters: 29  },
  { name: '2 Chronicles',     abbr: '2 Chr', testament: 'OT', maxChapters: 36  },
  { name: 'Ezra',             abbr: 'Ezra',  testament: 'OT', maxChapters: 10  },
  { name: 'Nehemiah',         abbr: 'Neh',   testament: 'OT', maxChapters: 13  },
  { name: 'Esther',           abbr: 'Esth',  testament: 'OT', maxChapters: 10  },
  { name: 'Job',              abbr: 'Job',   testament: 'OT', maxChapters: 42  },
  { name: 'Psalms',           abbr: 'Ps',    testament: 'OT', maxChapters: 150 },
  { name: 'Proverbs',         abbr: 'Prov',  testament: 'OT', maxChapters: 31  },
  { name: 'Ecclesiastes',     abbr: 'Eccl',  testament: 'OT', maxChapters: 12  },
  { name: 'Song of Solomon',  abbr: 'Song',  testament: 'OT', maxChapters: 8   },
  { name: 'Isaiah',           abbr: 'Isa',   testament: 'OT', maxChapters: 66  },
  { name: 'Jeremiah',         abbr: 'Jer',   testament: 'OT', maxChapters: 52  },
  { name: 'Lamentations',     abbr: 'Lam',   testament: 'OT', maxChapters: 5   },
  { name: 'Ezekiel',          abbr: 'Ezek',  testament: 'OT', maxChapters: 48  },
  { name: 'Daniel',           abbr: 'Dan',   testament: 'OT', maxChapters: 12  },
  { name: 'Hosea',            abbr: 'Hos',   testament: 'OT', maxChapters: 14  },
  { name: 'Joel',             abbr: 'Joel',  testament: 'OT', maxChapters: 3   },
  { name: 'Amos',             abbr: 'Amos',  testament: 'OT', maxChapters: 9   },
  { name: 'Obadiah',          abbr: 'Obad',  testament: 'OT', maxChapters: 1   },
  { name: 'Jonah',            abbr: 'Jonah', testament: 'OT', maxChapters: 4   },
  { name: 'Micah',            abbr: 'Mic',   testament: 'OT', maxChapters: 7   },
  { name: 'Nahum',            abbr: 'Nah',   testament: 'OT', maxChapters: 3   },
  { name: 'Habakkuk',         abbr: 'Hab',   testament: 'OT', maxChapters: 3   },
  { name: 'Zephaniah',        abbr: 'Zeph',  testament: 'OT', maxChapters: 3   },
  { name: 'Haggai',           abbr: 'Hag',   testament: 'OT', maxChapters: 2   },
  { name: 'Zechariah',        abbr: 'Zech',  testament: 'OT', maxChapters: 14  },
  { name: 'Malachi',          abbr: 'Mal',   testament: 'OT', maxChapters: 4   },
  // ── New Testament ──────────────────────────────────────────────────────────
  { name: 'Matthew',          abbr: 'Matt',  testament: 'NT', maxChapters: 28  },
  { name: 'Mark',             abbr: 'Mark',  testament: 'NT', maxChapters: 16  },
  { name: 'Luke',             abbr: 'Luke',  testament: 'NT', maxChapters: 24  },
  { name: 'John',             abbr: 'John',  testament: 'NT', maxChapters: 21  },
  { name: 'Acts',             abbr: 'Acts',  testament: 'NT', maxChapters: 28  },
  { name: 'Romans',           abbr: 'Rom',   testament: 'NT', maxChapters: 16  },
  { name: '1 Corinthians',    abbr: '1 Cor', testament: 'NT', maxChapters: 16  },
  { name: '2 Corinthians',    abbr: '2 Cor', testament: 'NT', maxChapters: 13  },
  { name: 'Galatians',        abbr: 'Gal',   testament: 'NT', maxChapters: 6   },
  { name: 'Ephesians',        abbr: 'Eph',   testament: 'NT', maxChapters: 6   },
  { name: 'Philippians',      abbr: 'Phil',  testament: 'NT', maxChapters: 4   },
  { name: 'Colossians',       abbr: 'Col',   testament: 'NT', maxChapters: 4   },
  { name: '1 Thessalonians',  abbr: '1 Th',  testament: 'NT', maxChapters: 5   },
  { name: '2 Thessalonians',  abbr: '2 Th',  testament: 'NT', maxChapters: 3   },
  { name: '1 Timothy',        abbr: '1 Tim', testament: 'NT', maxChapters: 6   },
  { name: '2 Timothy',        abbr: '2 Tim', testament: 'NT', maxChapters: 4   },
  { name: 'Titus',            abbr: 'Titus', testament: 'NT', maxChapters: 3   },
  { name: 'Philemon',         abbr: 'Phlm',  testament: 'NT', maxChapters: 1   },
  { name: 'Hebrews',          abbr: 'Heb',   testament: 'NT', maxChapters: 13  },
  { name: 'James',            abbr: 'Jas',   testament: 'NT', maxChapters: 5   },
  { name: '1 Peter',          abbr: '1 Pet', testament: 'NT', maxChapters: 5   },
  { name: '2 Peter',          abbr: '2 Pet', testament: 'NT', maxChapters: 3   },
  { name: '1 John',           abbr: '1 Jn',  testament: 'NT', maxChapters: 5   },
  { name: '2 John',           abbr: '2 Jn',  testament: 'NT', maxChapters: 1   },
  { name: '3 John',           abbr: '3 Jn',  testament: 'NT', maxChapters: 1   },
  { name: 'Jude',             abbr: 'Jude',  testament: 'NT', maxChapters: 1   },
  { name: 'Revelation',       abbr: 'Rev',   testament: 'NT', maxChapters: 22  },
];

const TRANSLATIONS = [
  // ── Common Modern ──────────────────────────────────────────────────────────
  { abbr: 'NIV',    name: 'New International Version' },
  { abbr: 'ESV',    name: 'English Standard Version' },
  { abbr: 'NLT',    name: 'New Living Translation' },
  { abbr: 'NASB',   name: 'New American Standard Bible' },
  { abbr: 'NASB95', name: 'NASB 1995' },
  { abbr: 'CSB',    name: 'Christian Standard Bible' },
  { abbr: 'NET',    name: 'New English Translation' },
  { abbr: 'GW',     name: "GOD'S WORD Translation" },
  { abbr: 'CEV',    name: 'Contemporary English Version' },
  { abbr: 'GNT',    name: 'Good News Translation' },
  { abbr: 'ERV',    name: 'Easy-to-Read Version' },
  { abbr: 'NCV',    name: 'New Century Version' },
  { abbr: 'MEV',    name: 'Modern English Version' },
  // ── Classic ────────────────────────────────────────────────────────────────
  { abbr: 'KJV',    name: 'King James Version' },
  { abbr: 'NKJV',   name: 'New King James Version' },
  { abbr: 'NRSV',   name: 'New Revised Standard Version' },
  { abbr: 'RSV',    name: 'Revised Standard Version' },
  { abbr: 'ASV',    name: 'American Standard Version' },
  { abbr: 'YLT',    name: "Young's Literal Translation" },
  // ── Amplified / Paraphrase ─────────────────────────────────────────────────
  { abbr: 'AMP',    name: 'Amplified Bible' },
  { abbr: 'AMPC',   name: 'Amplified Bible, Classic Edition' },
  { abbr: 'MSG',    name: 'The Message' },
  { abbr: 'TLB',    name: 'The Living Bible' },
  { abbr: 'TPT',    name: 'The Passion Translation' },
  // ── Study / Specialty ──────────────────────────────────────────────────────
  { abbr: 'HCSB',   name: 'Holman Christian Standard Bible' },
  { abbr: 'ICB',    name: "International Children's Bible" },
  { abbr: 'WEB',    name: 'World English Bible' },
  { abbr: 'NIV84',  name: 'New International Version (1984)' },
];
